CREATE TABLE Routes (
    RouteID INT IDENTITY PRIMARY KEY,
    RouteNumber NVARCHAR(10) NOT NULL UNIQUE,
    RouteName NVARCHAR(255) NOT NULL,
    TicketPrice DECIMAL(10, 2) NOT NULL
);

CREATE TABLE BusModels (
    ModelID INT IDENTITY PRIMARY KEY,
    ModelName NVARCHAR(100) NOT NULL,
    Manufacturer NVARCHAR(100) NULL,
    SeatCount INT NOT NULL
);

CREATE TABLE BusStatuses (
    StatusID INT IDENTITY PRIMARY KEY,
    StatusName NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Buses (
    BusID INT IDENTITY PRIMARY KEY,
    ModelID INT NOT NULL,
    StatusID INT NOT NULL,
    LicensePlate NVARCHAR(15) NOT NULL UNIQUE,
    YearOfManufacture INT NOT NULL
);

CREATE TABLE Employees (
    EmployeeID INT IDENTITY PRIMARY KEY,
    LastName NVARCHAR(50) NOT NULL,
    FirstName NVARCHAR(50) NOT NULL,
    Patronymic NVARCHAR(50) NULL,
    HireDate DATE NOT NULL
);

CREATE TABLE Roles (
    RoleID INT IDENTITY PRIMARY KEY,
    RoleName NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE EmployeeRoles (
    EmployeeID INT NOT NULL,
    RoleID INT NOT NULL,
    PRIMARY KEY (EmployeeID, RoleID),
);

CREATE TABLE Trips (
    TripID INT IDENTITY PRIMARY KEY,
    RouteID INT NOT NULL,
    BusID INT NOT NULL,
    DriverID INT NOT NULL,
    StartTime DATETIME2 NOT NULL,
    EndTime DATETIME2 NULL,
    TicketsSold INT NOT NULL DEFAULT 0,
);

CREATE TABLE ConductorAssignments (
    TripID INT NOT NULL,
    ConductorID INT NOT NULL,
    PRIMARY KEY (TripID, ConductorID),
);

CREATE TABLE MaintenanceLog (
    LogID INT IDENTITY PRIMARY KEY,
    BusID INT NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NULL,
    Description NVARCHAR(MAX) NOT NULL,
    Cost DECIMAL(10, 2) NULL,
);
GO
